config/routes.rb
Rails.application.routes.draw do
  resources :games

  devise_for :users, :skip => [:registrations] do
     get 'signup' => 'devise/registrations#new', :as => :new_user_registration
     post 'signup' => 'devise/registrations#create', :as => :user_registration
     get 'users/cancel' => 'devise/registrations#cancel', :as => :cancel_user_registration
     get 'users/edit' => 'devise/registrations#edit', :as => :edit_user_registration
     put 'users' => 'devise/registrations#update'
     delete 'users/cancel' => 'devise/registrations#destroy'
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    get 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :projects

  resources :posts

  root 'welcome#index'

  get '/landing' => 'welcome#index'
  get '/contact' => 'welcome#contact'
  get '/manifesto' => 'welcome#manifesto'
  get '/search' => 'welcome#search'

  get '/jellyvision' => 'welcome#jellyvision'

  get '/admin' => 'admin#index'

end

app/views/admin/index.html.erb
<h1>Admin Interface</h1>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
   |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Login", new_user_session_path, method: :get, :class => 'navbar-link'  %>
<% end %>


<% if current_user %>
<p>Create, Edit, and Delete Posts and Projects.</p>

<!-- POSTS  -->
<h2>Posts</h2>
<p>create <%= link_to 'new post', new_post_path %>.</p>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="2">Admin Options</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to "#{post.title}", post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<!-- PROJECTS -->
<h2>Projects</h2>
<p>create <%= link_to 'new project', new_project_path %>.</p>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="2">Admin Options</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to "#{project.name}", project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>

<p>Sorry, you don't belong here :) Why don't you go read some <%= link_to "blog posts", "/posts" %> or check out my <%= link_to "latest projects", "/projects" %>?</p>

<% end %>