config/routes.rb
Rails.application.routes.draw do
  resources :games

  devise_for :users, :skip => [:registrations] do
     get 'signup' => 'devise/registrations#new', :as => :new_user_registration
     post 'signup' => 'devise/registrations#create', :as => :user_registration
     get 'users/cancel' => 'devise/registrations#cancel', :as => :cancel_user_registration
     get 'users/edit' => 'devise/registrations#edit', :as => :edit_user_registration
     put 'users' => 'devise/registrations#update'
     delete 'users/cancel' => 'devise/registrations#destroy'
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    get 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :projects

  resources :posts

  root 'welcome#index'

  get '/landing' => 'welcome#index'
  get '/contact' => 'welcome#contact'
  get '/manifesto' => 'welcome#manifesto'
  get '/search' => 'welcome#search'

  get '/jellyvision' => 'welcome#jellyvision'

  get '/admin' => 'admin#index'

end

app/models/game.rb
class Game < ActiveRecord::Base

  # Slug Functionality
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  # Pagination Search
  def self.search(search, page)
    # paginate :per_page => 5, :page => page,
    #          :conditions => ['title like ?', "%#{search}%"],
    #          :order => 'title'
    order('created_at DESC').where('name LIKE ?', "%#{search}%").paginate(page: page, per_page: 8)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.search(params[:search], params[:page])
  end

  # GET /games/1
  # GET /games/1.json
  def show
    # Get random games
    @random_games = []
    game_array = Game.all
    @random_games = game_array - [@game]

    if request.path != game_path(@game)
      redirect_to @game, status: :moved_permanently
    end
  end

  # GET /games/new
  def new
    if current_user
      @game = Game.new
    else
      redirect_to root_url
    end
  end

  # GET /games/1/edit
  def edit
    if current_user
    else
      redirect_to root_url
    end
  end

  # POST /games
  # POST /games.json
  def create
    if current_user
      @game = Game.new(game_params)
      respond_to do |format|
        if @game.save
          format.html { redirect_to @game, notice: 'Game was successfully created.' }
          format.json { render :show, status: :created, location: @game }
        else
          format.html { render :new }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    if current_user
      respond_to do |format|
        if @game.update(game_params)
          format.html { redirect_to @game, notice: 'Game was successfully updated.' }
          format.json { render :show, status: :ok, location: @game }
        else
          format.html { render :edit }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    if current_user
      @game.destroy
      respond_to do |format|
        format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.friendly.find(params[:id])
      #@game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :body, :image, :published)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_card_game.html.erb
<%= content_tag :div, class: "post-card", :onclick => "location.href=\'#{game_path(post)}\'" do %>
  <div style="text-align: center; display: inline-block;"><%= image_tag post.image, width: "100%" %></div>
  <h3 style="margin: 0px 4px; text-align: center; font-weight: bold; font-family: 'Roboto Slab', serif;"><%= post.name %></h2>
  <br>
  <p style="margin: 0px 4px; text-align: center;"><%= post.description %></p>
  <br>
  <p style="font-size: 1em; font-style: italic; font-weight: bold;"><%= post.created_at.to_date.strftime("%B %d, %Y") %></p>
<% end %>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <button id="buttonHTML" ng-click="current_tab = 1">HTML</button>
  <button id="buttonPreview" ng-click="current_tab = 2">Preview</button>

  <!-- HTML -->
  <div id="viewHTML">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_area :name, cols: 120, rows: 2 %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, cols: 120, rows: 5 %>
    </div>
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body, cols: 120, rows: 20, "class"=>"mytextarea" %>
    </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.text_area :image, cols: 120, rows: 1 %>
    </div>
    <div class="field">
      <%= f.label :published %><br>
      <%= f.check_box :published %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
  <!-- Preview -->
  <div id="viewPreview">

    <h1 style="color: #3333CC;"><strong><span class="title-container"></span></strong></h1>
    <h2><span class="dek-container"></span></h2>

    <img class="image_container" src="image.jpg" width="100%"/>

    <!-- <p style="text-align:center"></p> -->

    <div class="body-container">
      <div class="demo-box">Demonstration Box</div>
    </div>
  </div>

<% end %>

app/views/games/_share_game.html.erb
<div class="row clearfix">
  <div class="col-md-12 column text-center">
    <div class="container">
    <h4 style="font-weight: bold;">Thank you for checking out my work. If you would like to learn more about the game, please <a href="/contact">contact me</a>.<br><br> If you found it interesting or know someone who would like it, please consider sharing it around.</h4>
    </div>
  </div>
  <div class="col-md-3 column text-center"></div>
  <div class="col-md-2 column text-center">
    <button class="share-button share-twitter">
      <%= link_to "http://twitter.com/home?status=\"#{@post.name}\" by @djdewitt https://djdewitt.com#{project_path(@post)}", :target => "_blank" do %>
      <i class="fa fa-twitter-square" style="font-size: 5em;"></i>
      <% end %>
    </button>
  </div>
  <div class="col-md-2 column text-center">
    <button class="share-button share-facebook">
      <%= link_to "https://www.facebook.com/sharer/sharer.php?u=", :title => "Share on Facebook", :target => "_blank" do %>
      <i class="fa fa-facebook-square" style="font-size: 5em;"></i>
      <% end %>
    </button>
  </div>
  <div class="col-md-2 column text-center">
    <button class="share-button share-email">
      <%= link_to "mailto:?subject=Check out '#{@post.name}' from DJDeWitt.com&body=I think you would find this game interesting!%0D%0A%0D%0A#{@post.name}: #{@post.description}%0D%0A%0D%0A%0D%0Alink: https://djdewitt.com#{project_path(@post)}" do %>
      <i class="fa fa-share-square" style="font-size: 5em;"></i>
      <% end %>
    </button>
  </div>
  <div class="col-md-3 column text-center"></div>
</div>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row clearfix">
  <div class="col-md-12 column" style="background-color: #eee;">
    <div class="container">
<h1 style="color: #3333CC;"><strong style="font-family: 'Roboto Slab', serif;">My Games</strong></h1>
<h2>Below you'll find a portfolio of my lovingly crafted video games. Using <a href="https://www.yoyogames.com/studio">GameMaker: Studio</a>, I make personal games for computers, tablets, and smartphones. If you're interested in my work, <a href="/contact">please reach out!</a></h2>
    </div>
  </div>
</div>
<div class="row clearfix text-center"  style="margin-bottom: 16px;">
  <div class="container">
    <% @games.each do |game| %>
      <%= render 'games/card_game', :post => game %>
    <% end %>
  </div>
</div>
<br>
<%= will_paginate @games %>
<br>

app/views/games/new.html.erb
<div class="row clearfix">
  <div class="col-md-12 column" style="background-color: #eee;">
    <div class="container">
      <h1>New Game</h1>
      <%= render 'form' %>
      <%= link_to 'Back', games_path %>
    </div>
  </div>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row clearfix">
  <div class="col-md-12 column" style="background-color: #eee;">
    <div class="container">
      <h1 style="color: #3333CC;"><strong style="font-family: 'Roboto Slab', serif;"><%= @game.name %></strong></h1>
      <h2><%= @game.description %></h2>
    </div>
  </div>
  <div class="col-md-12 column" style="background-color: white;">
    <div class="container">
      <p style="text-align:center"><%= image_tag "#{@game.image}", width: "100%" %></p>
      <div style="font-size: 1.5em;"><%= @game.body.html_safe %></div>
    </div>
  </div>
  <div style="background-color: #eee;">
    <div class="container">
      <%= render 'games/share_game', :@post => @game %>
      <br>
      <h4 style="text-align: center; font-weight: bold;">Please check out some of my other games below:</h4>
    </div>
  </div>
  <div class="row clearfix text-center" style="background-color: white;">
    <div class="container">
      <% @random_games.each do |post| %>
        <%= render 'games/card_game', :post => post %>
      <% end %>
    </div>
  </div>
</div>