config/routes.rb
Rails.application.routes.draw do
  resources :games

  devise_for :users, :skip => [:registrations] do
     get 'signup' => 'devise/registrations#new', :as => :new_user_registration
     post 'signup' => 'devise/registrations#create', :as => :user_registration
     get 'users/cancel' => 'devise/registrations#cancel', :as => :cancel_user_registration
     get 'users/edit' => 'devise/registrations#edit', :as => :edit_user_registration
     put 'users' => 'devise/registrations#update'
     delete 'users/cancel' => 'devise/registrations#destroy'
    get 'signin' => 'devise/sessions#new', :as => :new_user_session
    post 'signin' => 'devise/sessions#create', :as => :user_session
    get 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :projects

  resources :posts

  root 'welcome#index'

  get '/landing' => 'welcome#index'
  get '/contact' => 'welcome#contact'
  get '/manifesto' => 'welcome#manifesto'
  get '/search' => 'welcome#search'

  get '/jellyvision' => 'welcome#jellyvision'

  get '/admin' => 'admin#index'

end

app/models/project.rb
class Project < ActiveRecord::Base

  # Slug Functionality
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  # Pagination Search
  def self.search(search, page)
    # paginate :per_page => 5, :page => page,
    #          :conditions => ['title like ?', "%#{search}%"],
    #          :order => 'title'
    order('created_at DESC').where('name LIKE ?', "%#{search}%").paginate(page: page, per_page: 8)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    # @projects = Project.all
    @projects = Project.search(params[:search], params[:page])
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    # Get random projects
    @random_projects = []
    project_array = Project.all
    @random_projects = project_array - [@project]

    if request.path != project_path(@project)
      redirect_to @project, status: :moved_permanently
    end
  end

  # GET /projects/new
  def new
    if current_user
      @project = Project.new
    else
      redirect_to root_url
    end
  end

  # GET /projects/1/edit
  def edit
    if current_user
    else
      redirect_to root_url
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    if current_user
      @project = Project.new(project_params)
      respond_to do |format|
        if @project.save
          format.html { redirect_to @project, notice: 'Project was successfully created.' }
          format.json { render :show, status: :created, location: @project }
        else
          format.html { render :new }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if current_user
      respond_to do |format|
        if @project.update(project_params)
          format.html { redirect_to @project, notice: 'Project was successfully updated.' }
          format.json { render :show, status: :ok, location: @project }
        else
          format.html { render :edit }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_url
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    if current_user
      @project.destroy
      respond_to do |format|
        format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
      #@project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :body, :image)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_card_project.html.erb
<%= content_tag :div, class: "post-card", :onclick => "location.href=\'#{project_path(post)}\'" do %>
  <div style="text-align: center; display: inline-block;"><%= image_tag post.image, width: "100%" %></div>
  <h3 style="margin: 0px 4px; text-align: center; font-weight: bold; font-family: 'Roboto Slab', serif;"><%= post.name %></h2>
  <br>
  <p style="margin: 0px 4px; text-align: center;"><%= post.description %></p>
  <br>
  <p style="font-size: 1em; font-style: italic; font-weight: bold;"><%= post.created_at.to_date.strftime("%B %d, %Y") %></p>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, cols: 80, rows: 10 %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, cols: 80, rows: 20 %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_share_project.html.erb
<div class="row clearfix">
  <div class="col-md-12 column text-center">
    <div class="container">
    <h4 style="font-weight: bold;">Thank you for checking out my work. If you would like to learn more about the project or have an idea for it, please <a href="/contact">contact me</a>.<br><br> If you found it interesting or know someone who would like it, please consider sharing it around.</h4>
    </div>
  </div>
  <div class="col-md-3 column text-center"></div>
  <div class="col-md-2 column text-center">
    <button class="share-button share-twitter">
      <%= link_to "http://twitter.com/home?status=\"#{@post.name}\" by @djdewitt https://djdewitt.com#{project_path(@post)}", :target => "_blank" do %>
      <i class="fa fa-twitter-square" style="font-size: 5em;"></i>
      <% end %>
    </button>
  </div>
  <div class="col-md-2 column text-center">
    <button class="share-button share-facebook">
      <%= link_to "https://www.facebook.com/sharer/sharer.php?u=", :title => "Share on Facebook", :target => "_blank" do %>
      <i class="fa fa-facebook-square" style="font-size: 5em;"></i>
      <% end %>
    </button>
  </div>
  <div class="col-md-2 column text-center">
    <button class="share-button share-email">
      <%= link_to "mailto:?subject=Check out '#{@post.name}' from DJDeWitt.com&body=I think you would find this project interesting!%0D%0A%0D%0A#{@post.name}: #{@post.description}%0D%0A%0D%0A%0D%0Alink: https://djdewitt.com#{project_path(@post)}" do %>
      <i class="fa fa-share-square" style="font-size: 5em;"></i>
      <% end %>
    </button>
  </div>
  <div class="col-md-3 column text-center"></div>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row clearfix">
  <div class="col-md-12 column" style="background-color: #eee;">
    <div class="container">
      <h1 style="color: #3333CC;"><strong style="font-family: 'Roboto Slab', serif;">My Projects</strong></h1>
      <h2>Below you'll find a portfolio of my web development projects. I'm interested in building tools that are interesting, entertaining, edifying, and genuinely helpful. If you have an idea for a project or something here strikes your fancy, <a href="/contact">please reach out!</a></h2>
    </div>
  </div>
</div>
<div class="row clearfix text-center">
  <div class="container">
    <% @projects.each do |project| %>
      <%= render 'projects/card_project', :post => project %>
    <% end %>
  </div>
</div>
<br>
<%= will_paginate @projects %>
<br>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row clearfix">
  <div class="col-md-12 column" style="background-color: #eee;">
    <div class="container">
      <h1 style="color: #3333CC;"><strong style="font-family: 'Roboto Slab', serif;"><%= @project.name %></strong></h1>
      <h2><%= @project.description %></h2>
    </div>
  </div>
  <div class="col-md-12 column" style="background-color: white;">
    <div class="container">
      <p style="text-align:center"><%= image_tag "#{@project.image}", width: "100%" %></p>
      <p style="font-size: 1.5em;"><%= @project.body.html_safe %></p>
    </div>
  </div>

  <div style="background-color: #eee;">
    <div class="container">
      <%= render 'projects/share_project', :@post => @project %>
      <br>
      <h4 style="text-align: center; font-weight: bold;">Please check out some of my other projects below:</h4>
    </div>
  </div>
  <div class="row clearfix text-center" style="background-color: white;">
    <div class="container">
      <% @random_projects.each do |post| %>
        <%= render 'projects/card_project', :post => post %>
      <% end %>
    </div>
  </div>
</div>